/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.kalkulator.compleks;

import com.sun.webkit.dom.EventImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author NURUL MUSTOFA
 */
public class speed_calculate extends javax.swing.JFrame {

    /**
     * Creates new form speed_calculate
     */
    String angka;
    public speed_calculate() {
        initComponents();
        int AngkaSatu = 1;
        int AngkaDua = 2;
        int AngkaTiga = 3;
        int AngkaEmpat = 4;
        int AngkaLima = 5;
        int AngkaEnam = 6;
        int AngkaTujuh = 7;
        int AngkaDelapan = 8;
        int AngkaSembilan = 9;
        int AngkaNol = 0;
        char btnKoma = ',';
        angka = "";
    }
    public void convert(){
        String ConvertFrom = cmbFrom.getSelectedItem().toString();
        String ConvertTo = cmbTo.getSelectedItem().toString();
        if (ConvertFrom.equals("Knots")) {
            if (ConvertTo.equals("Miles Per Hour")) {
                JOptionPane.showMessageDialog(this, "udah bener kodinggannya bro");
            }else{
                JOptionPane.showMessageDialog(this, "di miles to yang salah");
            }
        } else {
            JOptionPane.showMessageDialog(this, "di kmh yang salah");
        }
    }
    public void tekanTombolKoma(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        speedcalculate_pane = new javax.swing.JPanel();
        My_Calculator = new javax.swing.JLabel();
        AngkaSembilan = new javax.swing.JButton();
        AngkaDelapan = new javax.swing.JButton();
        AngkaTujuh = new javax.swing.JButton();
        btnKoma = new javax.swing.JButton();
        btn_convert = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_ce = new javax.swing.JButton();
        AngkaEnam = new javax.swing.JButton();
        AngkaLima = new javax.swing.JButton();
        AngkaEmpat = new javax.swing.JButton();
        lblFrom = new javax.swing.JLabel();
        cmbFrom = new javax.swing.JComboBox<>();
        cmbTo = new javax.swing.JComboBox<>();
        lblTo = new javax.swing.JLabel();
        AngkaDua = new javax.swing.JButton();
        AngkaSatu = new javax.swing.JButton();
        AngkaTiga = new javax.swing.JButton();
        AngkaNol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        speedcalculate_pane.setBackground(new java.awt.Color(0, 255, 255));
        speedcalculate_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        My_Calculator.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        My_Calculator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        My_Calculator.setText("My Calculator");
        speedcalculate_pane.add(My_Calculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 300, -1));

        AngkaSembilan.setText("9");
        AngkaSembilan.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaSembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaSembilanActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaSembilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        AngkaDelapan.setText("8");
        AngkaDelapan.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaDelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaDelapanActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaDelapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        AngkaTujuh.setText("7");
        AngkaTujuh.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaTujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaTujuhActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaTujuh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        btnKoma.setText(",");
        btnKoma.setPreferredSize(new java.awt.Dimension(96, 45));
        btnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomaActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(btnKoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        btn_convert.setText("Convert");
        btn_convert.setPreferredSize(new java.awt.Dimension(96, 45));
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(btn_convert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        btn_hapus.setText("<--");
        btn_hapus.setPreferredSize(new java.awt.Dimension(96, 45));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        btn_ce.setText("CE");
        btn_ce.setPreferredSize(new java.awt.Dimension(96, 45));
        btn_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(btn_ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        AngkaEnam.setText("6");
        AngkaEnam.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaEnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaEnamActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaEnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        AngkaLima.setText("5");
        AngkaLima.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaLimaActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaLima, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        AngkaEmpat.setText("4");
        AngkaEmpat.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaEmpatActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaEmpat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        lblFrom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrom.setText("0");
        speedcalculate_pane.add(lblFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cmbFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometer Per Hour", "Miles Per Hour", "Knots", "Centimetres Per Second", "Meters Per Second", "Feet Per Second" }));
        cmbFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFromActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(cmbFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, -1));

        cmbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometer Per Hour", "Miles Per Hour", "Knots", "Centimetres Per Second", "Meters Per Second", "Feet Per Second" }));
        cmbTo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbToKeyReleased(evt);
            }
        });
        speedcalculate_pane.add(cmbTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, -1));

        lblTo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTo.setText("0");
        speedcalculate_pane.add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        AngkaDua.setText("2");
        AngkaDua.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaDuaActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaDua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        AngkaSatu.setText("1");
        AngkaSatu.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaSatuActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaSatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        AngkaTiga.setText("3");
        AngkaTiga.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaTigaActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaTiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        AngkaNol.setText("0");
        AngkaNol.setPreferredSize(new java.awt.Dimension(96, 45));
        AngkaNol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AngkaNolActionPerformed(evt);
            }
        });
        speedcalculate_pane.add(AngkaNol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        getContentPane().add(speedcalculate_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceActionPerformed
        // TODO add your handling code here:
        lblFrom.setText("0");
        lblTo.setText("0");
    }//GEN-LAST:event_btn_ceActionPerformed

    private void AngkaDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaDuaActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '2');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '2');
        }        
    }//GEN-LAST:event_AngkaDuaActionPerformed

    private void cmbToKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbToKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbToKeyReleased

    private void AngkaDelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaDelapanActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '8');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '8');
        }      
    }//GEN-LAST:event_AngkaDelapanActionPerformed

    private void AngkaTujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaTujuhActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '7');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '7');
        }
    }//GEN-LAST:event_AngkaTujuhActionPerformed

    private void AngkaSembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaSembilanActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '9');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '9');
        }
    }//GEN-LAST:event_AngkaSembilanActionPerformed

    private void AngkaEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaEmpatActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '4');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '4');
        }
    }//GEN-LAST:event_AngkaEmpatActionPerformed

    private void AngkaLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaLimaActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '5');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '5');
        }
    }//GEN-LAST:event_AngkaLimaActionPerformed

    private void AngkaEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaEnamActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '6');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '6');
        }
    }//GEN-LAST:event_AngkaEnamActionPerformed

    private void AngkaSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaSatuActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '1');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '1');
        }
    }//GEN-LAST:event_AngkaSatuActionPerformed

    private void AngkaTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaTigaActionPerformed
        // TODO add your handling code here:        
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '3');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '3');
        }
    }//GEN-LAST:event_AngkaTigaActionPerformed

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed
        // TODO add your handling code here:
        double result;
        double AmbilNilai = Double.parseDouble(lblFrom.getText());
        if (cmbFrom.getSelectedItem().equals("Miles Per Hour") && cmbTo.getSelectedItem().equals("Kilometer Per Hour")) {
            result = 1.609 * AmbilNilai;
            lblTo.setText(String.format("%.3f",result) + " Kilometers Per Hour");
        }else if(cmbFrom.getSelectedItem().equals("Kilometer Per Hour") && cmbTo.getSelectedItem().equals("Miles Per Hour")){
            result = AmbilNilai / 1.609;
            lblTo.setText(String.format("%.3f",result) + " Kilometers Per Hour");
        }
    }//GEN-LAST:event_btn_convertActionPerformed

    private void btnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomaActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_koma = lblFrom.getText();
        if (Ambil_nilai_koma.contains(".")) {
            JOptionPane.showMessageDialog(null, "Dilarang Menggunakan double ','");
            System.exit(0);
        }else{
            lblFrom.setText(Ambil_nilai_koma + '.');
        }
    }//GEN-LAST:event_btnKomaActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int length = lblFrom.getText().length();
        int number = lblFrom.getText().length() - 1;
        String store;
//      declare  two integer variable i.e lenght and number.
//      length() is a method to return the length of the string.
//      example :-
//      if textfield contain 'car'
//      then the length is 3.
//      length() -1 means subtract 1 from length

        if (length > 0) {
            StringBuilder back = new StringBuilder(lblFrom.getText());
            back.deleteCharAt(number);
            store = back.toString();
            lblFrom.setText(store);
        /*
            declare 'store' variable which datatype is string.
            
            StringBuilder is Creates empty string builder, which is used to store
            Strings.
            
            back is object of StringBuilder.
            
            (jtextfield1.getText()); -> the value of the text field is stored in StringBuilder 'back'
            
            back.deleteChartAt(number); -> deleteChartAt() is a method used to delete a single character from
            specific position.
            
            (number); here i declared 'number' variable bcoz i want delete length 1 by one.
            
            store = back.toString(); -> convert StringBuilder 'back' into string.
            bcoz Textfield only take String Values.
            
            jtextFiel1.settext(store); -> 'store' variable set in setText() method.
            */                   
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void cmbFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFromActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbFromActionPerformed

    private void AngkaNolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AngkaNolActionPerformed
        // TODO add your handling code here:
        String Ambil_nilai_nul = lblFrom.getText();
        if (Ambil_nilai_nul.equals("0")) {
            Ambil_nilai_nul = "";    
            lblFrom.setText(Ambil_nilai_nul + '0');
        }else{
            lblFrom.setText(Ambil_nilai_nul + '0');
        }
    }//GEN-LAST:event_AngkaNolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(speed_calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(speed_calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(speed_calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(speed_calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new speed_calculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AngkaDelapan;
    private javax.swing.JButton AngkaDua;
    private javax.swing.JButton AngkaEmpat;
    private javax.swing.JButton AngkaEnam;
    private javax.swing.JButton AngkaLima;
    private javax.swing.JButton AngkaNol;
    private javax.swing.JButton AngkaSatu;
    private javax.swing.JButton AngkaSembilan;
    private javax.swing.JButton AngkaTiga;
    private javax.swing.JButton AngkaTujuh;
    private javax.swing.JLabel My_Calculator;
    private javax.swing.JButton btnKoma;
    private javax.swing.JButton btn_ce;
    private javax.swing.JButton btn_convert;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JComboBox<String> cmbFrom;
    private javax.swing.JComboBox<String> cmbTo;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel speedcalculate_pane;
    // End of variables declaration//GEN-END:variables
}
